//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class meeting
    {
        public meeting()
        {
            this.meeting_attenders = new HashSet<meeting_attender>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int group_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string interval_type { get; set; }
        public string occur_day { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
    
        public virtual group group { get; set; }
        public virtual ICollection<meeting_attender> meeting_attenders { get; set; }
    }
}
