// <auto-generated />
namespace HCI.HciDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class add_mails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_mails));
        
        string IMigrationMetadata.Id
        {
            get { return "201411201717025_add_mails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
