// <auto-generated />
namespace HCI.HciDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class seed_data_02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seed_data_02));
        
        string IMigrationMetadata.Id
        {
            get { return "201411142112124_seed_data_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
