//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public group()
        {
            this.group_memberships = new HashSet<group_membership>();
            this.meetings = new HashSet<meeting>();
            this.rel_groups_studyfields = new HashSet<rel_group_studyfield>();
            this.requests = new HashSet<request>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int owner_id { get; set; }
        public string description { get; set; }
        public string course_no { get; set; }
        public int max_member_number { get; set; }
        public int is_closed { get; set; }
    
        public virtual ICollection<group_membership> group_memberships { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<meeting> meetings { get; set; }
        public virtual ICollection<rel_group_studyfield> rel_groups_studyfields { get; set; }
        public virtual ICollection<request> requests { get; set; }
    }
}
