//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public schedule()
        {
            this.users = new HashSet<user>();
            this.events = new HashSet<@event>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<user> users { get; set; }
        public virtual ICollection<@event> events { get; set; }
    }
}
