//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCI
{
    using System;
    using System.Collections.Generic;
    
    public partial class study_fields
    {
        public study_fields()
        {
            this.rel_groups_studyfields = new HashSet<rel_groups_studyfield>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<rel_groups_studyfield> rel_groups_studyfields { get; set; }
    }
}
