//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class degree_level
    {
        public degree_level()
        {
            this.users = new HashSet<user>();
        }
    
        public int id { get; set; }
        public string degree_level_desc { get; set; }
    
        public virtual ICollection<user> users { get; set; }
    }
}
