//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_schedule
    {
        public int id { get; set; }
        public int event_id { get; set; }
        public string interval_type { get; set; }
        public string occur_day { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
    
        public virtual @event @event { get; set; }
    }
}
